version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - postgres_db
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jobrunr
      POSTGRES_PASSWORD: secret
