name: Maven and Docker Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '19'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)
